//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCContactBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public Organization()
        {
            this.People = new HashSet<Person>();
        }
    
        public int OrganizationID { get; set; }
        public string OrganizationName { get; set; }
        public string Address { get; set; }
        public int ContactNo { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Person> People { get; set; }
    }
}
